name: build

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: sudo npm install

      - name: Run Build
        run: sudo npm run build

      - name: Install Xvfb
        run: sudo apt-get install xvfb

      - name: Run Test By Xvfb
        run: sudo xvfb-run --auto-servernum npm run test